# Generated by ChatGPT on 2026-01-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_name',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='updates/'),
        ),
    ]
