# Generated by Django 5.2.8 on 2026-01-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogData', '0002_post_imagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
